id: opecha:P003094
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG13794
  title: གཞི་ཐམས་ཅད་ཡོད་སྨྲའི་ལུགས་ཀྱི་ཕམ་བཞིའི་མཐའ་དཔྱད་སློབ་དཔོན་ཡོན་ཏན་འོད་ཀྱི་དགོངས་རྒྱན།
  volume: ''
  author: ''
