id: P003094
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG13794
  title: གཞི་ཐམས་ཅད་ཡོད་སྨྲའི་ལུགས་ཀྱི་ཕམ་བཞིའི་མཐའ་དཔྱད་སློབ་དཔོན་ཡོན་ཏན་འོད་ཀྱི་དགོངས་རྒྱན།
  author: ''
  volumes:
    f6a09a695c4348818563b736f709741f:
      image_group_id: I1KG15377
      title: ''
      volume_number: 1
      total_pages: 76
      base_file: v001.txt
