id: I9D82D376
legacy_id: P003094
ocr_import_info:
  bdrc_scan_id: W1KG13794
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T03:34:11'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T04:55:48.285846+00:00'
last_modified: 2022-08-27 12:56:02.805734
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG13794
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG13794
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཞི་ཐམས་ཅད་ཡོད་སྨྲའི་ལུགས་ཀྱི་ཕམ་བཞིའི་མཐའ་དཔྱད་སློབ་དཔོན་ཡོན་ཏན་འོད་ཀྱི་དགོངས་རྒྱན།
  author: ཐུབ་བསྟན་ཡོན་ཏན་བཟང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.9630981224480103
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG15377:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15377
      total_pages: 76
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG15377.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9630981224480103
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
